using System.Text.Json.Serialization;
using System.Xml.Serialization;

namespace OpenDeepWiki.Chat.Providers.WeChat;

#region XML message models

/// <summary>
/// WeChat incoming message base structure (XML format)
/// </summary>
[XmlRoot("xml")]
public class WeChatXmlMessage
{
    /// <summary>
    /// Developer WeChat ID
    /// </summary>
    [XmlElement("ToUserName")]
    public string ToUserName { get; set; } = string.Empty;
    
    /// <summary>
    /// Sender account (OpenID)
    /// </summary>
    [XmlElement("FromUserName")]
    public string FromUserName { get; set; } = string.Empty;
    
    /// <summary>
    /// Message creation time (integer)
    /// </summary>
    [XmlElement("CreateTime")]
    public long CreateTime { get; set; }
    
    /// <summary>
    /// Message type: text, image, voice, video, shortvideo, location, link, event
    /// </summary>
    [XmlElement("MsgType")]
    public string MsgType { get; set; } = string.Empty;
    
    /// <summary>
    /// Message ID (64-bit integer)
    /// </summary>
    [XmlElement("MsgId")]
    public long MsgId { get; set; }
    
    /// <summary>
    /// Message data ID (used for message deduplication)
    /// </summary>
    [XmlElement("MsgDataId")]
    public string? MsgDataId { get; set; }
    
    /// <summary>
    /// Text message content
    /// </summary>
    [XmlElement("Content")]
    public string? Content { get; set; }
    
    /// <summary>
    /// Image URL (generated by system)
    /// </summary>
    [XmlElement("PicUrl")]
    public string? PicUrl { get; set; }
    
    /// <summary>
    /// Image/voice/video message media ID
    /// </summary>
    [XmlElement("MediaId")]
    public string? MediaId { get; set; }
    
    /// <summary>
    /// Voice format: amr, speex
    /// </summary>
    [XmlElement("Format")]
    public string? Format { get; set; }
    
    /// <summary>
    /// Voice recognition result (available only when voice recognition is enabled)
    /// </summary>
    [XmlElement("Recognition")]
    public string? Recognition { get; set; }
    
    /// <summary>
    /// Video message thumbnail media ID
    /// </summary>
    [XmlElement("ThumbMediaId")]
    public string? ThumbMediaId { get; set; }
    
    /// <summary>
    /// Geographic location latitude
    /// </summary>
    [XmlElement("Location_X")]
    public double? LocationX { get; set; }
    
    /// <summary>
    /// Geographic location longitude
    /// </summary>
    [XmlElement("Location_Y")]
    public double? LocationY { get; set; }
    
    /// <summary>
    /// Map zoom level
    /// </summary>
    [XmlElement("Scale")]
    public int? Scale { get; set; }
    
    /// <summary>
    /// Geographic location info
    /// </summary>
    [XmlElement("Label")]
    public string? Label { get; set; }
    
    /// <summary>
    /// Message title
    /// </summary>
    [XmlElement("Title")]
    public string? Title { get; set; }
    
    /// <summary>
    /// Message description
    /// </summary>
    [XmlElement("Description")]
    public string? Description { get; set; }
    
    /// <summary>
    /// Message URL
    /// </summary>
    [XmlElement("Url")]
    public string? Url { get; set; }
    
    /// <summary>
    /// Event type (only for event messages)
    /// </summary>
    [XmlElement("Event")]
    public string? Event { get; set; }
    
    /// <summary>
    /// Event KEY value
    /// </summary>
    [XmlElement("EventKey")]
    public string? EventKey { get; set; }
    
    /// <summary>
    /// QR code ticket
    /// </summary>
    [XmlElement("Ticket")]
    public string? Ticket { get; set; }
}

/// <summary>
/// WeChat encrypted message structure
/// </summary>
[XmlRoot("xml")]
public class WeChatEncryptedMessage
{
    /// <summary>
    /// Encrypted message content
    /// </summary>
    [XmlElement("Encrypt")]
    public string Encrypt { get; set; } = string.Empty;
    
    /// <summary>
    /// Message signature
    /// </summary>
    [XmlElement("MsgSignature")]
    public string? MsgSignature { get; set; }
    
    /// <summary>
    /// Timestamp
    /// </summary>
    [XmlElement("TimeStamp")]
    public string? TimeStamp { get; set; }
    
    /// <summary>
    /// Nonce
    /// </summary>
    [XmlElement("Nonce")]
    public string? Nonce { get; set; }
}

#endregion

#region API response models

/// <summary>
/// WeChat API base response
/// </summary>
public class WeChatApiResponse
{
    /// <summary>
    /// Error code (0 indicates success)
    /// </summary>
    [JsonPropertyName("errcode")]
    public int ErrorCode { get; set; }
    
    /// <summary>
    /// Error message
    /// </summary>
    [JsonPropertyName("errmsg")]
    public string ErrorMessage { get; set; } = string.Empty;
}

/// <summary>
/// WeChat Access Token response
/// </summary>
public class WeChatTokenResponse : WeChatApiResponse
{
    /// <summary>
    /// Access Token
    /// </summary>
    [JsonPropertyName("access_token")]
    public string AccessToken { get; set; } = string.Empty;
    
    /// <summary>
    /// Expiration time (seconds)
    /// </summary>
    [JsonPropertyName("expires_in")]
    public int ExpiresIn { get; set; }
}

/// <summary>
/// WeChat customer service message send response
/// </summary>
public class WeChatSendMessageResponse : WeChatApiResponse
{
    /// <summary>
    /// Message ID (returned by some APIs)
    /// </summary>
    [JsonPropertyName("msgid")]
    public long? MsgId { get; set; }
}

#endregion

#region Customer service message request models

/// <summary>
/// WeChat customer service message base request
/// </summary>
public class WeChatCustomMessageRequest
{
    /// <summary>
    /// Receiver OpenID
    /// </summary>
    [JsonPropertyName("touser")]
    public string ToUser { get; set; } = string.Empty;
    
    /// <summary>
    /// Message type: text, image, voice, video, music, news, mpnews, msgmenu, wxcard, miniprogrampage
    /// </summary>
    [JsonPropertyName("msgtype")]
    public string MsgType { get; set; } = string.Empty;
    
    /// <summary>
    /// Text message content
    /// </summary>
    [JsonPropertyName("text")]
    public WeChatTextContent? Text { get; set; }
    
    /// <summary>
    /// Image message content
    /// </summary>
    [JsonPropertyName("image")]
    public WeChatMediaContent? Image { get; set; }
    
    /// <summary>
    /// Voice message content
    /// </summary>
    [JsonPropertyName("voice")]
    public WeChatMediaContent? Voice { get; set; }
    
    /// <summary>
    /// Video message content
    /// </summary>
    [JsonPropertyName("video")]
    public WeChatVideoContent? Video { get; set; }
    
    /// <summary>
    /// Music message content
    /// </summary>
    [JsonPropertyName("music")]
    public WeChatMusicContent? Music { get; set; }
    
    /// <summary>
    /// News (rich text) message content
    /// </summary>
    [JsonPropertyName("news")]
    public WeChatNewsContent? News { get; set; }
}


/// <summary>
/// WeChat text message content
/// </summary>
public class WeChatTextContent
{
    /// <summary>
    /// Text content
    /// </summary>
    [JsonPropertyName("content")]
    public string Content { get; set; } = string.Empty;
}

/// <summary>
/// WeChat media message content (image, voice)
/// </summary>
public class WeChatMediaContent
{
    /// <summary>
    /// Media ID
    /// </summary>
    [JsonPropertyName("media_id")]
    public string MediaId { get; set; } = string.Empty;
}

/// <summary>
/// WeChat video message content
/// </summary>
public class WeChatVideoContent
{
    /// <summary>
    /// Media ID
    /// </summary>
    [JsonPropertyName("media_id")]
    public string MediaId { get; set; } = string.Empty;
    
    /// <summary>
    /// Thumbnail media ID
    /// </summary>
    [JsonPropertyName("thumb_media_id")]
    public string? ThumbMediaId { get; set; }
    
    /// <summary>
    /// Video title
    /// </summary>
    [JsonPropertyName("title")]
    public string? Title { get; set; }
    
    /// <summary>
    /// Video description
    /// </summary>
    [JsonPropertyName("description")]
    public string? Description { get; set; }
}

/// <summary>
/// WeChat music message content
/// </summary>
public class WeChatMusicContent
{
    /// <summary>
    /// Music title
    /// </summary>
    [JsonPropertyName("title")]
    public string? Title { get; set; }
    
    /// <summary>
    /// Music description
    /// </summary>
    [JsonPropertyName("description")]
    public string? Description { get; set; }
    
    /// <summary>
    /// Music URL
    /// </summary>
    [JsonPropertyName("musicurl")]
    public string MusicUrl { get; set; } = string.Empty;
    
    /// <summary>
    /// High-quality music URL
    /// </summary>
    [JsonPropertyName("hqmusicurl")]
    public string? HqMusicUrl { get; set; }
    
    /// <summary>
    /// Thumbnail media ID
    /// </summary>
    [JsonPropertyName("thumb_media_id")]
    public string ThumbMediaId { get; set; } = string.Empty;
}

/// <summary>
/// WeChat news message content
/// </summary>
public class WeChatNewsContent
{
    /// <summary>
    /// News message article list
    /// </summary>
    [JsonPropertyName("articles")]
    public List<WeChatArticle> Articles { get; set; } = new();
}

/// <summary>
/// WeChat news message article
/// </summary>
public class WeChatArticle
{
    /// <summary>
    /// Title
    /// </summary>
    [JsonPropertyName("title")]
    public string Title { get; set; } = string.Empty;
    
    /// <summary>
    /// Description
    /// </summary>
    [JsonPropertyName("description")]
    public string? Description { get; set; }
    
    /// <summary>
    /// URL to redirect to on click
    /// </summary>
    [JsonPropertyName("url")]
    public string Url { get; set; } = string.Empty;
    
    /// <summary>
    /// Image URL for the news message
    /// </summary>
    [JsonPropertyName("picurl")]
    public string? PicUrl { get; set; }
}

#endregion

#region Message type constants

/// <summary>
/// WeChat message type constants
/// </summary>
public static class WeChatMsgType
{
    /// <summary>
    /// Text message
    /// </summary>
    public const string Text = "text";
    
    /// <summary>
    /// Image message
    /// </summary>
    public const string Image = "image";
    
    /// <summary>
    /// Voice message
    /// </summary>
    public const string Voice = "voice";
    
    /// <summary>
    /// Video message
    /// </summary>
    public const string Video = "video";
    
    /// <summary>
    /// Short video message
    /// </summary>
    public const string ShortVideo = "shortvideo";
    
    /// <summary>
    /// Location message
    /// </summary>
    public const string Location = "location";
    
    /// <summary>
    /// Link message
    /// </summary>
    public const string Link = "link";
    
    /// <summary>
    /// Event message
    /// </summary>
    public const string Event = "event";
    
    /// <summary>
    /// Music message
    /// </summary>
    public const string Music = "music";
    
    /// <summary>
    /// News message
    /// </summary>
    public const string News = "news";
}

/// <summary>
/// WeChat event type constants
/// </summary>
public static class WeChatEventType
{
    /// <summary>
    /// Subscribe event
    /// </summary>
    public const string Subscribe = "subscribe";
    
    /// <summary>
    /// Unsubscribe event
    /// </summary>
    public const string Unsubscribe = "unsubscribe";
    
    /// <summary>
    /// Scan QR code with parameters event
    /// </summary>
    public const string Scan = "SCAN";
    
    /// <summary>
    /// Report location event
    /// </summary>
    public const string Location = "LOCATION";
    
    /// <summary>
    /// Click menu to pull message event
    /// </summary>
    public const string Click = "CLICK";
    
    /// <summary>
    /// Click menu to redirect URL event
    /// </summary>
    public const string View = "VIEW";
}

#endregion
